### ISSUE TITLE
QA tools/warnings

### ISSUE THREAD

**Issue by aawiseman** [openstreetmap/iD#3130]
There was some discussion on the HOT email list about some potential QA tools or QA-related warnings in iD that would be helpful:
* [x] 1. when there are non-squared buildings (especially when there are a lot of them) -- #2624 and #3085 mention this
* [ ] 2. duplicated/overlapping polygons of the same/similar tags (which can be an issue when people map outside their squares, or just sloppy/quick editing)
* [x] 3. roads overlapping/going through polygons, especially buildings
* [X] 4. disconnected roads (that are just floating and not connected to anything, which is bad for HOT responses and for rendering, mentioned in #1281) (#3786)
* [x] 5. roads that cross and should intersect but aren't connected to each other
* [ ] 6. roads that are connected with buildings (I think due to snapping) - #476 mentions this, maybe it's not an error? But to me a road shouldn't be coincident with a building edge, which sometime happens

**Comment by aawiseman** [comment]
Oh another one, it might be good to highlight features that have fixme= in them!

**Comment by bhousel** [comment]
I'm all for adding validation to iD where it makes sense, but I don't want to overwhelm new users with a bunch of messages about things that they won't understand, and might not even be responsible for. 

Dedicated QA tools like Keepright and Osmose do great jobs at catching a lot of these conditions, and HOT has a pretty effective structure in place to have new mappers' edits reviewed by experienced validators.  

The last thing I want to do is turn away enthusiastic new mappers by nagging them about their work.  

But I think this list is a good start.. I'll think about these items and see if we can make some improvements, either in the iD training materials or the pre-save validations that iD runs.

**Comment by aawiseman** [comment]
I think in the pre-save validations would be great.

Or something related, maybe a little popup that comes up as you are mapping, for example if you do ten buildings in a row that aren't squared. That may be a heavier lift, however.

**Comment by quincylvania** [comment]
So a lot's changed in validation since this issue was posted!

- We've done points 1, 3, 4, and 5.
- I think #5977 covers point 6.
- Point 2 is already covered for buildings and will be covered for water by #7050. I'm not sure that other types of area crossings are a large concern but we can open separate issues for them if needed.

I'm closing this since remaining actionable items are pretty well covered by other issues 👍
