### ISSUE TITLE
iD v2 release checklist

### ISSUE THREAD

**Issue by bhousel** [openstreetmap/iD#3234]
We are getting close to finishing the refactor of iD into modules!  🎊 

I've tagged all related work with the [iD v2 label](https://github.com/openstreetmap/iD/labels/iD%20v2).  Many thanks to @tmcw and @kepta for making this refactor a reality..

Once this work is finished, iD v2.x will look and feel the same as v1.x but will have a different programming structure.  This will benefit us by making it easier to 1. keep iD's dependencies up to date 2. share iD code with other OSM projects, 3. keep current the with ever-changing [state of the art in JavaScript development](https://medium.com/javascript-and-opinions/state-of-the-art-javascript-in-2016-ab67fc68eb0b).

Sites that have forked or embedded iD may need to make some minimal changes to their code.  Mostly because things have new names now as we move away from global variables. 

It would be really cool (but not essential) to wrap this up before the [July 23 State of the Map conference in Seattle](http://stateofthemap.us/).  I'm going to be there talking about iD, and hosting a workshop on Monday.  If you're in town, say hi!

Before releasing iD v2, let's make sure to:
- [x] update [API.md](https://github.com/openstreetmap/iD/blob/master/API.md)
- [ ] update [ARCHITECTURE.md](https://github.com/openstreetmap/iD/blob/master/ARCHITECTURE.md)
- [x] check all `index.html` files and example code
- [x] check performance to make sure it hasn't regressed
- [x] test across all supported browsers (Chrome, Firefox, Safari, IE11, Edge)

**Comment by gmaclennan** [comment]
Thanks for this @bhousel. I wouldn't want it to be a blocker, but [async storage](https://github.com/openstreetmap/iD/issues/3239) would probably introduce breaking changes for forked or embedded iD users, so a v2 release might be a good time to include it.

**Comment by bhousel** [comment]
> I wouldn't want it to be a blocker, but async storage would probably introduce breaking changes for forked or embedded iD users, so a v2 release might be a good time to include it.

I'll check it this week, shouldn't be a blocker.   In fact, the best part about the refactor (for me anyway) is how easy it is now to pull in and depend on third party libraries.
