### ISSUE TITLE
alpha3 design priorities

### ISSUE THREAD

**Issue by jfirebaugh** [openstreetmap/iD#895]
Putting together a prioritized list for @samanpwbb's work Wednesday/Thursday. Feel free to edit. These will be the design issues we want to try to tackle before alpha3. Higher priorities first.
- [x] Inspector layout (#834)
- [ ] Other inspector/preset work -- needs to be detailed
- [x] Icon for rotate (#896)
- [x] Icon for simplify (#910)
- [x] Truncated commit UI (#816)
- [x] Improve tooltips (#669, #828, #829)
- [x] Loading indicator (#430)
- [x] Footer improvements (#830)
- [x] Landuse colors (#761)
- [ ] Illustration for success page (#421)
